---

- name: Ensure pip is installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: False

- block:
    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp
    - name: install pip
      command: python /tmp/get-pip.py
    - name: delete get-pip-py
      file:
        path: /tmp/get-pip.py
        state: absent
  when: pip_is_installed.failed

# Specified version because of https://github.com/ansible/ansible/issues/17495
- name: Install docker-py 1.9.0 to fix Ansible issue 17495
  pip:
    name: docker-py
    version: 1.9.0
    state: present
  when: ansible_version is defined and ansible_version.full | version_compare('2.2.0.0', '<')

- name: Install docker-py
  pip:
    name: docker-py
    state: present
  when: (ansible_version is not defined) or (ansible_version is defined and ansible_version.full | version_compare('2.2.0.0', '>='))